/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActiveBadge: typeof import('./src/components/active-badge.vue')['default']
    AvatarTitleGroup: typeof import('./src/components/avatar-title-group.vue')['default']
    ClientTable: typeof import('./src/components/tables/client-table.vue')['default']
    EditBtn: typeof import('./src/components/edit-btn.vue')['default']
    LoadingButton: typeof import('./src/components/loading-button.vue')['default']
    LoadingSelect: typeof import('./src/components/loading-select.vue')['default']
    Notice: typeof import('./src/components/Notice.vue')['default']
    PageNavigation: typeof import('./src/components/page-navigation.vue')['default']
    RoleBadge: typeof import('./src/components/role-badge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerTable: typeof import('./src/components/tables/server-table.vue')['default']
    Tabs: typeof import('./src/components/campaigns/tabs.vue')['default']
    TypesBadge: typeof import('./src/components/campaigns/types-badge.vue')['default']
  }
}
