/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account/change-password': RouteRecordInfo<'/account/change-password', '/account/change-password', Record<never, never>, Record<never, never>>,
    '/account/preferences': RouteRecordInfo<'/account/preferences', '/account/preferences', Record<never, never>, Record<never, never>>,
    '/account/profile': RouteRecordInfo<'/account/profile', '/account/profile', Record<never, never>, Record<never, never>>,
    '/authentication/forgot-password': RouteRecordInfo<'/authentication/forgot-password', '/authentication/forgot-password', Record<never, never>, Record<never, never>>,
    '/authentication/login': RouteRecordInfo<'/authentication/login', '/authentication/login', Record<never, never>, Record<never, never>>,
    '/authentication/reset-password': RouteRecordInfo<'/authentication/reset-password', '/authentication/reset-password', Record<never, never>, Record<never, never>>,
    '/campaigns/campaign-details': RouteRecordInfo<'/campaigns/campaign-details', '/campaigns/campaign-details', Record<never, never>, Record<never, never>>,
    '/campaigns/campaigns-list': RouteRecordInfo<'/campaigns/campaigns-list', '/campaigns/campaigns-list', Record<never, never>, Record<never, never>>,
    '/campaigns/column-config': RouteRecordInfo<'/campaigns/column-config', '/campaigns/column-config', Record<never, never>, Record<never, never>>,
    '/campaigns/create-campaign-modal': RouteRecordInfo<'/campaigns/create-campaign-modal', '/campaigns/create-campaign-modal', Record<never, never>, Record<never, never>>,
    '/campaigns/edit-campaign': RouteRecordInfo<'/campaigns/edit-campaign', '/campaigns/edit-campaign', Record<never, never>, Record<never, never>>,
    '/dashboard/components/activity': RouteRecordInfo<'/dashboard/components/activity', '/dashboard/components/activity', Record<never, never>, Record<never, never>>,
    '/dashboard/components/products': RouteRecordInfo<'/dashboard/components/products', '/dashboard/components/products', Record<never, never>, Record<never, never>>,
    '/dashboard/components/projection': RouteRecordInfo<'/dashboard/components/projection', '/dashboard/components/projection', Record<never, never>, Record<never, never>>,
    '/dashboard/components/revenue': RouteRecordInfo<'/dashboard/components/revenue', '/dashboard/components/revenue', Record<never, never>, Record<never, never>>,
    '/dashboard/components/revenue-by-loc': RouteRecordInfo<'/dashboard/components/revenue-by-loc', '/dashboard/components/revenue-by-loc', Record<never, never>, Record<never, never>>,
    '/dashboard/components/sales': RouteRecordInfo<'/dashboard/components/sales', '/dashboard/components/sales', Record<never, never>, Record<never, never>>,
    '/dashboard/components/stats': RouteRecordInfo<'/dashboard/components/stats', '/dashboard/components/stats', Record<never, never>, Record<never, never>>,
    '/dashboard/components/widget-recent-activity': RouteRecordInfo<'/dashboard/components/widget-recent-activity', '/dashboard/components/widget-recent-activity', Record<never, never>, Record<never, never>>,
    '/dashboard/components/widget-stat-icon': RouteRecordInfo<'/dashboard/components/widget-stat-icon', '/dashboard/components/widget-stat-icon', Record<never, never>, Record<never, never>>,
    '/dashboard/dashboard': RouteRecordInfo<'/dashboard/dashboard', '/dashboard/dashboard', Record<never, never>, Record<never, never>>,
    '/error/error-401': RouteRecordInfo<'/error/error-401', '/error/error-401', Record<never, never>, Record<never, never>>,
    '/error/error-404': RouteRecordInfo<'/error/error-404', '/error/error-404', Record<never, never>, Record<never, never>>,
    '/products/column-config': RouteRecordInfo<'/products/column-config', '/products/column-config', Record<never, never>, Record<never, never>>,
    '/products/edit-product': RouteRecordInfo<'/products/edit-product', '/products/edit-product', Record<never, never>, Record<never, never>>,
    '/products/product-modal': RouteRecordInfo<'/products/product-modal', '/products/product-modal', Record<never, never>, Record<never, never>>,
    '/products/products-list': RouteRecordInfo<'/products/products-list', '/products/products-list', Record<never, never>, Record<never, never>>,
    '/tenants/column-config': RouteRecordInfo<'/tenants/column-config', '/tenants/column-config', Record<never, never>, Record<never, never>>,
    '/tenants/edit-tenant': RouteRecordInfo<'/tenants/edit-tenant', '/tenants/edit-tenant', Record<never, never>, Record<never, never>>,
    '/tenants/edit-tenant-modal': RouteRecordInfo<'/tenants/edit-tenant-modal', '/tenants/edit-tenant-modal', Record<never, never>, Record<never, never>>,
    '/tenants/register-tenant-modal': RouteRecordInfo<'/tenants/register-tenant-modal', '/tenants/register-tenant-modal', Record<never, never>, Record<never, never>>,
    '/tenants/tenants-list': RouteRecordInfo<'/tenants/tenants-list', '/tenants/tenants-list', Record<never, never>, Record<never, never>>,
    '/users/column-config': RouteRecordInfo<'/users/column-config', '/users/column-config', Record<never, never>, Record<never, never>>,
    '/users/edit-user': RouteRecordInfo<'/users/edit-user', '/users/edit-user', Record<never, never>, Record<never, never>>,
    '/users/edit-user-modal': RouteRecordInfo<'/users/edit-user-modal', '/users/edit-user-modal', Record<never, never>, Record<never, never>>,
    '/users/register-user-modal': RouteRecordInfo<'/users/register-user-modal', '/users/register-user-modal', Record<never, never>, Record<never, never>>,
    '/users/users-list': RouteRecordInfo<'/users/users-list', '/users/users-list', Record<never, never>, Record<never, never>>,
  }
}
